matrix:
  include:
    - language: python
      python: 3.6
      cache:
        pip: true
      install:
        - pip install -r backend/requirements.txt
      before_script:
        - cd backend
        - rm -f */migrations/0*.py 2> /dev/null
        - ./manage.py makemigrations && ./manage.py migrate
      script:
        - python manage.py test
        - python manage.py runserver

    - language: node_js
      node_js:
        - "stable"
      before_script:
        - cd frontend
        - rm -rf node_modules && rm -f package-lock.json
        - npm install
      script:
        - npm test
        - CI=false && npm run build
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: stock-portfolio-rohan
        skip_cleanup: true
        on:
          branch: master
