matrix:
  include:
    - language: python
      python: 3.6
      cache:
        pip: true
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - language: node_js
      node_js:
        - "8"
      before_script:
        - npm install
      script:
        - npm test
        - CI=false && npm run build
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: stock-portfolio-rohan
        skip_cleanup: true
        on:
          branch: master
